// Package converter provides Man Page (troff/nroff) converter for AsciiDoc AST.
package converter

import (
	"bytes"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/haimiyahya/asciidoc-parser-go/internal/ast"
	"github.com/haimiyahya/asciidoc-parser-go/internal/inline"
)

// ManPageConverter converts an AsciiDoc AST to troff/nroff Man Page format.
type ManPageConverter struct {
	// manual section (1-8, default 1)
	section string

	// manual name (command name)
	manualName string

	// manual date (default: current date)
	date string

	// manual source (organization)
	source string

	// manual title (default: "User Commands")
	title string

	// indent level
	indent string
}

// NewManPageConverter creates a new Man Page converter.
func NewManPageConverter() *ManPageConverter {
	return &ManPageConverter{
		section:    "1",
		date:       time.Now().Format("2006-01-02"),
		source:     "",
		title:      "User Commands",
		manualName: "",
		indent:     "",
	}
}

// WithSection sets the manual section (1-8).
func (c *ManPageConverter) WithSection(section string) *ManPageConverter {
	c.section = section
	return c
}

// WithManualName sets the manual name (command name).
func (c *ManPageConverter) WithManualName(name string) *ManPageConverter {
	c.manualName = name
	return c
}

// WithDate sets the manual date.
func (c *ManPageConverter) WithDate(date string) *ManPageConverter {
	c.date = date
	return c
}

// WithSource sets the manual source (organization).
func (c *ManPageConverter) WithSource(source string) *ManPageConverter {
	c.source = source
	return c
}

// WithTitle sets the manual title.
func (c *ManPageConverter) WithTitle(title string) *ManPageConverter {
	c.title = title
	return c
}

// escapeTroff escapes special troff characters.
func (c *ManPageConverter) escapeTroff(s string) string {
	// Escape backslashes first
	s = strings.ReplaceAll(s, "\\", "\\")
	// Escape dots at start of lines
	s = strings.ReplaceAll(s, ".", "\\&.")
	// Escape dashes (minus signs)
	s = strings.ReplaceAll(s, "-", "\\-")
	return s
}

// Convert converts document to Man Page format.
func (c *ManPageConverter) Convert(doc *ast.NodeDocument, w io.Writer) error {
	var buf bytes.Buffer

	// Extract manual name from document title if not set
	if c.manualName == "" && doc.Header != nil && doc.Header.Title != "" {
		// Use first word of title as manual name
		parts := strings.Fields(doc.Header.Title)
		if len(parts) > 0 {
			c.manualName = strings.ToUpper(parts[0])
		}
	}

	// If still no manual name, use a default
	if c.manualName == "" {
		c.manualName = "COMMAND"
	}

	// Write TH (Title Header) - .TH name section date source title
	buf.WriteString(fmt.Sprintf(".TH \"%s\" \"%s\" \"%s\"", c.manualName, c.section, c.date))
	if c.source != "" {
		buf.WriteString(fmt.Sprintf(" \"%s\"", c.source))
	}
	if c.title != "" {
		buf.WriteString(fmt.Sprintf(" \"%s\"", c.title))
	}
	buf.WriteString("\n")

	// Write standard comment
	buf.WriteString(".\" Automatically generated from AsciiDoc source\n")
	buf.WriteString(".\" Generated by asciidoc-parser-go\n")

	// Process document into sections
	var nameSection bytes.Buffer
	var synopsisSection bytes.Buffer
	var descriptionSection bytes.Buffer
	var optionsSection bytes.Buffer
	var examplesSection bytes.Buffer
	var otherSections bytes.Buffer

	// Track current section
	currentSection := ""

	for _, block := range doc.Blocks {
		switch n := block.(type) {
		case *ast.NodeSection:
			// Map section titles to man page sections
			sectionTitle := strings.ToLower(n.Title)
			currentSection = c.mapSectionToManPage(sectionTitle)

			// Write content to appropriate buffer
			switch currentSection {
			case "NAME":
				// NAME section is handled specially
				if len(n.Children) > 0 {
					c.convertNodeContent(n.Children, &nameSection)
				}
			case "SYNOPSIS":
				buf.WriteString("\n.SH \"SYNOPSIS\"\n")
				c.convertNodeContent(n.Children, &synopsisSection)
			case "DESCRIPTION":
				buf.WriteString("\n.SH \"DESCRIPTION\"\n")
				c.convertNodeContent(n.Children, &descriptionSection)
			case "OPTIONS":
				buf.WriteString("\n.SH \"OPTIONS\"\n")
				c.convertNodeContent(n.Children, &optionsSection)
			case "EXAMPLES":
				buf.WriteString("\n.SH \"EXAMPLES\"\n")
				c.convertNodeContent(n.Children, &examplesSection)
			default:
				// Other sections
				c.writeSectionHeader(n.Title, &otherSections)
				c.convertNodeContent(n.Children, &otherSections)
			}

		case *ast.NodeParagraph:
			// Paragraph - add to appropriate section based on context
			paraContent := c.formatParagraph(n)
			if currentSection == "NAME" {
				nameSection.WriteString(paraContent)
			} else if currentSection == "SYNOPSIS" {
				synopsisSection.WriteString(paraContent)
			} else if currentSection == "DESCRIPTION" {
				descriptionSection.WriteString(paraContent)
			} else if currentSection == "OPTIONS" {
				optionsSection.WriteString(paraContent)
			} else if currentSection == "EXAMPLES" {
				examplesSection.WriteString(paraContent)
			} else {
				otherSections.WriteString(paraContent)
			}

		case *ast.NodeList:
			// List - special handling for options
			listContent := c.formatList(n)
			if currentSection == "OPTIONS" {
				optionsSection.WriteString(listContent)
			} else if currentSection == "DESCRIPTION" {
				descriptionSection.WriteString(listContent)
			} else {
				otherSections.WriteString(listContent)
			}

		case *ast.NodeLiteral:
			// Code/literal block - use .IP or .nf/.fi
			literalContent := c.formatLiteral(n)
			if currentSection == "EXAMPLES" {
				examplesSection.WriteString(literalContent)
			} else {
				otherSections.WriteString(literalContent)
			}

		case *ast.NodeBlock:
			// Delimited block
			blockContent := c.formatBlock(n)
			otherSections.WriteString(blockContent)

		case *ast.AdmonitionNode:
			// Admonition - use .PP with bold tag
			admonitionContent := c.formatAdmonition(n)
			otherSections.WriteString(admonitionContent)

		case *ast.Table:
			// Table - format as text with alignment
			tableContent := c.formatTable(n)
			if currentSection == "DESCRIPTION" {
				descriptionSection.WriteString(tableContent)
			} else if currentSection == "OPTIONS" {
				optionsSection.WriteString(tableContent)
			} else if currentSection == "EXAMPLES" {
				examplesSection.WriteString(tableContent)
			} else {
				otherSections.WriteString(tableContent)
			}
		}
	}

	// Write NAME section first (required)
	if nameSection.Len() > 0 {
		buf.WriteString("\n.SH \"NAME\"\n")
		buf.Write(nameSection.Bytes())
	}

	// Write synopsis if present
	if synopsisSection.Len() > 0 {
		buf.Write(synopsisSection.Bytes())
	}

	// Write description if present
	if descriptionSection.Len() > 0 {
		buf.Write(descriptionSection.Bytes())
	}

	// Write options if present
	if optionsSection.Len() > 0 {
		buf.Write(optionsSection.Bytes())
	}

	// Write examples if present
	if examplesSection.Len() > 0 {
		buf.Write(examplesSection.Bytes())
	}

	// Write other sections
	buf.Write(otherSections.Bytes())

	// Write to output
	_, err := w.Write(buf.Bytes())
	return err
}

// mapSectionToManPage maps AsciiDoc section titles to Man Page sections.
func (c *ManPageConverter) mapSectionToManPage(title string) string {
	switch {
	case strings.Contains(title, "name") && strings.Contains(title, "synopsis"):
		return "NAME"
	case strings.Contains(title, "name"):
		return "NAME"
	case strings.Contains(title, "synopsis"):
		return "SYNOPSIS"
	case strings.Contains(title, "description"):
		return "DESCRIPTION"
	case strings.Contains(title, "options"):
		return "OPTIONS"
	case strings.Contains(title, "argument"):
		return "OPTIONS"
	case strings.Contains(title, "example"):
		return "EXAMPLES"
	case strings.Contains(title, "exit"):
		return "EXIT STATUS"
	case strings.Contains(title, "return"):
		return "RETURN VALUE"
	case strings.Contains(title, "environment"):
		return "ENVIRONMENT"
	case strings.Contains(title, "file"):
		return "FILES"
	case strings.Contains(title, "see also"):
		return "SEE ALSO"
	case strings.Contains(title, "bug"):
		return "BUGS"
	case strings.Contains(title, "author"):
		return "AUTHOR"
	case strings.Contains(title, "history"):
		return "HISTORY"
	default:
		return title
	}
}

// writeSectionHeader writes a section header in man format.
func (c *ManPageConverter) writeSectionHeader(title string, buf *bytes.Buffer) {
	buf.WriteString(fmt.Sprintf("\n.SH \"%s\"\n", strings.ToUpper(title)))
}

// convertNodeContent converts a list of nodes to man format.
func (c *ManPageConverter) convertNodeContent(nodes []ast.Node, buf *bytes.Buffer) {
	for _, node := range nodes {
		switch n := node.(type) {
		case *ast.NodeParagraph:
			buf.WriteString(c.formatParagraph(n))
		case *ast.NodeList:
			buf.WriteString(c.formatList(n))
		case *ast.NodeLiteral:
			buf.WriteString(c.formatLiteral(n))
		case *ast.NodeBlock:
			buf.WriteString(c.formatBlock(n))
		case *ast.AdmonitionNode:
			buf.WriteString(c.formatAdmonition(n))
		case *ast.Table:
			buf.WriteString(c.formatTable(n))
		}
	}
}

// formatParagraph formats a paragraph for man page.
func (c *ManPageConverter) formatParagraph(para *ast.NodeParagraph) string {
	var buf bytes.Buffer

	buf.WriteString(".PP\n")

	// Process inline nodes
	if len(para.InlineNodes) == 0 {
		buf.WriteString(c.escapeTroff(para.Text))
	} else {
		buf.WriteString(c.formatInlineText(para.Text, para.InlineNodes))
	}

	buf.WriteString("\n")

	return buf.String()
}

// formatInlineText formats text with inline nodes.
func (c *ManPageConverter) formatInlineText(text string, inlineNodes []interface{}) string {
	var buf bytes.Buffer

	lastEnd := 0
	for _, node := range inlineNodes {
		if inlineNode, ok := node.(*inline.Node); ok {
			startPos := inlineNode.StartPos
			// Write any text before this inline node
			if startPos > lastEnd {
				plainText := text[lastEnd:startPos]
				buf.WriteString(c.escapeTroff(plainText))
			}
			lastEnd = inlineNode.Position

			// Render the inline node
			buf.WriteString(c.formatInlineNode(inlineNode))
		}
	}

	// Write any remaining text after last inline node
	if lastEnd < len(text) {
		plainText := text[lastEnd:]
		buf.WriteString(c.escapeTroff(plainText))
	}

	return buf.String()
}

// formatInlineNode formats an inline node for man page.
func (c *ManPageConverter) formatInlineNode(node *inline.Node) string {
	var buf bytes.Buffer

	switch node.Type {
	case inline.NodeText:
		buf.WriteString(c.escapeTroff(node.Text))
	case inline.NodeBold:
		buf.WriteString(fmt.Sprintf("\\fB%s\\fR", c.escapeTroff(node.Text)))
	case inline.NodeItalic:
		buf.WriteString(fmt.Sprintf("\\fI%s\\fR", c.escapeTroff(node.Text)))
	case inline.NodeMonospace:
		buf.WriteString(fmt.Sprintf("\\fB%s\\fR", c.escapeTroff(node.Text)))
	case inline.NodeSubscript:
		buf.WriteString(fmt.Sprintf("\\d\\s-2%s\\s+2\\u", c.escapeTroff(node.Text)))
	case inline.NodeSuperscript:
		buf.WriteString(fmt.Sprintf("\\u\\s-2%s\\s+2\\d", c.escapeTroff(node.Text)))
	case inline.NodeLink:
		if node.Text != "" {
			buf.WriteString(fmt.Sprintf("\\fI%s\\fR", c.escapeTroff(node.Text)))
		} else {
			buf.WriteString(fmt.Sprintf("\\fI%s\\fR", c.escapeTroff(node.URL)))
		}
	case inline.NodeImage:
		alt := node.Alt
		if alt == "" {
			alt = node.Text
		}
		buf.WriteString(fmt.Sprintf("[Image: %s]", c.escapeTroff(alt)))
	case inline.NodeCrossRef:
		// Cross-reference: use RefText if available, otherwise use Ref
		text := node.RefText
		if text == "" {
			text = node.Ref
		}
		buf.WriteString(fmt.Sprintf("\\fI%s\\fR", c.escapeTroff(text)))
	}

	return buf.String()
}

// formatList formats a list for man page.
func (c *ManPageConverter) formatList(list *ast.NodeList) string {
	var buf bytes.Buffer

	if len(list.Items) == 0 {
		return ""
	}

	// Check if this is a variable list (definitions) - common for options
	item := list.Items[0]
	listItem, ok := item.(*ast.NodeListItem)
	if !ok {
		return ""
	}

	if listItem.Marker == "::" {
		// Variable list - use .TP for tagged paragraphs
		for _, item := range list.Items {
			if li, ok := item.(*ast.NodeListItem); ok {
				buf.WriteString(".TP\n")
				buf.WriteString(fmt.Sprintf(".B \"%s\"\n", c.escapeTroff(li.Term)))
				if li.Text != "" {
					buf.WriteString(c.escapeTroff(li.Text))
					buf.WriteString("\n")
				}
				if li.NestedList != nil {
					buf.WriteString(c.formatList(li.NestedList))
				}
			}
		}
	} else {
		// Regular list - use .IP for items
		for _, item := range list.Items {
			if li, ok := item.(*ast.NodeListItem); ok {
				buf.WriteString(".IP \\(bu 2\n")
				buf.WriteString(c.escapeTroff(li.Text))
				buf.WriteString("\n")
				if li.NestedList != nil {
					buf.WriteString(c.formatList(li.NestedList))
				}
			}
		}
	}

	return buf.String()
}

// formatTable formats a table for man page.
func (c *ManPageConverter) formatTable(table *ast.Table) string {
	var buf bytes.Buffer

	// Man pages have limited table support
	// We'll format tables as text with basic alignment

	buf.WriteString(".RS\n")
	buf.WriteString(".nf\n") // No fill

	// Write caption if present
	if table.Caption != "" {
		buf.WriteString(fmt.Sprintf("%s\n", c.escapeTroff(table.Caption)))
	}

	// Calculate column widths for alignment
	maxWidths := make([]int, table.ColumnCount())
	for _, row := range table.Rows {
		for i, cell := range row.Cells {
			text := cell.Text
			if len(text) > maxWidths[i] {
				maxWidths[i] = len(text)
			}
		}
	}

	// Write each row
	for _, row := range table.Rows {
		var rowText strings.Builder
		for i, cell := range row.Cells {
			text := c.escapeTroff(cell.Text)
			if i < len(row.Cells)-1 {
				// Pad to alignment width
				format := fmt.Sprintf("%%-%ds  ", maxWidths[i])
				rowText.WriteString(fmt.Sprintf(format, text))
			} else {
				rowText.WriteString(text)
			}
		}
		buf.WriteString(rowText.String())
		buf.WriteString("\n")
	}

	buf.WriteString(".fi\n")
	buf.WriteString(".RE\n")

	return buf.String()
}

// formatLiteral formats a literal block for man page.
func (c *ManPageConverter) formatLiteral(literal *ast.NodeLiteral) string {
	var buf bytes.Buffer

	buf.WriteString(".RS\n")
	buf.WriteString(".nf\n")

	for _, line := range literal.Lines {
		buf.WriteString(c.escapeTroff(line))
		buf.WriteString("\n")
	}

	buf.WriteString(".fi\n")
	buf.WriteString(".RE\n")

	return buf.String()
}

// formatBlock formats a delimited block for man page.
func (c *ManPageConverter) formatBlock(block *ast.NodeBlock) string {
	var buf bytes.Buffer

	// For most delimited blocks, indent the content
	buf.WriteString(".RS\n")

	content := strings.Join(block.Lines, "\n")
	buf.WriteString(c.escapeTroff(content))
	buf.WriteString("\n")

	buf.WriteString(".RE\n")

	return buf.String()
}

// formatAdmonition formats an admonition for man page.
func (c *ManPageConverter) formatAdmonition(admonition *ast.AdmonitionNode) string {
	var buf bytes.Buffer

	buf.WriteString(".PP\n")
	buf.WriteString(fmt.Sprintf("\\fB%s:\\fR %s\n",
		strings.ToUpper(admonition.Kind),
		c.escapeTroff(admonition.Text)))

	return buf.String()
}
